#!/bin/bash

set -o errexit
set -o xtrace

declare hostname=$(head --lines 1 $1 | awk '{print $3}')
declare revision=$(git rev-parse --short HEAD)

for file in $(ls -1 tests/spec/rainforest/*.rfml); do
  sed --in-place --expression "s/{{site.host}}/$hostname/" $file
done

until rainforest --token $RAINFOREST_TOKEN upload --test-folder tests/spec/rainforest; do
  sleep 5
done

git checkout tests/

rainforest --token $RAINFOREST_TOKEN \
           --description "$revision on $hostname" \
           --site-id $RAINFOREST_SITE_ID \
           --custom-url http://$hostname \
           --tag automated \
           run
